# Generated by Django 4.2.7 on 2025-12-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="identity_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="customer",
            name="passport_number",
            field=models.CharField(max_length=50),
        ),
    ]
