# Generated by Django 4.2.7 on 2025-12-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customer_identity_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
